name: boh_hummm
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Contains classes and methods for data persistence in SQLite.
  sqflite: ^2.4.2

  # Cross-platform path manipulation library for Dart.
  path: ^1.9.1

  # Firebase
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Allow the use of SQLite through the FFI interface in environments where SQLite is not natively available or
  # where access to native APIs is required. Allows mocking sqflite during flutter regular unit testing.
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true