// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsNW5gYoo83dgOeIUwLhlWFiJ-T_ggN4w',
    appId: '1:226266413723:android:cb5ac74d38d5935b1c643e',
    messagingSenderId: '226266413723',
    projectId: 'boh-hummm-app',
    storageBucket: 'boh-hummm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlqubTWyEJcObV1gjPdjAdLP9hGJ8igM',
    appId: '1:226266413723:ios:617525d3a4ee8c101c643e',
    messagingSenderId: '226266413723',
    projectId: 'boh-hummm-app',
    storageBucket: 'boh-hummm-app.firebasestorage.app',
    androidClientId: '226266413723-1b4anha66f532oq9ek6jmbqej16gnnh9.apps.googleusercontent.com',
    iosClientId: '226266413723-gptq5sub6tsqhvco3spoc9q6qpmoftu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bohHummm',
  );

}